'use client';

import { createContext, useContext, useState } from 'react';

const translations = {
  si: {
    app_name: 'ගොවි නැණ',
    tagline: 'ගොවි නැණ',
    subtitle: 'ඔබේ බෝග සෞඛ්‍ය සහකාරිය',
    subtitle2: 'Your Crop Health Assistant',
    sign_in: 'පුරනය වන්න',
    sign_in_sub: 'ගිණුමට ප්‍රවේශ වන්න',
    phone: 'දුරකථන අංකය',
    password: 'මුරපදය',
    forgot: 'මුරපදය අමතකද?',
    login_btn: 'පුරනය වන්න',
    no_account: 'ගිණුමක් නැද්ද?',
    register_link: 'ලියාපදිංචි වන්න',
    footer: '🌾 Empowering Sri Lankan Farmers',
    register_title: 'ලියාපදිංචි වන්න',
    register_sub: 'නව ගිණුමක් සාදන්න',
    full_name: 'සම්පූර්ණ නම',
    district: 'දිස්ත්‍රික්කය',
    district_placeholder: 'දිස්ත්‍රික්කය තෝරන්න',
    register_btn: 'ගිණුම සාදන්න',
    has_account: 'දැනටමත් ගිණුමක් ඇද්ද?',
    login_link: 'පුරනය වන්න',
    districts: [
      'කොළඹ', 'ගම්පහ', 'කළුතර', 'කඳි', 'මාතලේ', 'නුවරඑළිය',
      'ගාල්ල', 'මාතර', 'හම්බන්තොට', 'යාපනය', 'මන්නාරම', 'වවුනියාව',
      'අනුරාධපුර', 'පොළොන්නරුව', 'කුරුණෑගල', 'පුත්තලම', 'බදුල්ල',
      'මොණරාගල', 'රත්නපුර', 'කෑගල්ල', 'ත්‍රිකුණාමලය', 'මඩකළපුව', 'අම්පාර'
    ],
    // Scan page
scan_select_crop: 'බෝගය තෝරන්න',
scan_select_sub: 'රෝගය හඳුනා ගැනීමට',
scan_upload_img: 'ඡායාරූපයක් උඩුගත කරන්න',
scan_diseases: 'රෝග',
scan_loading: 'Model load වෙනවා...',
scan_loading_sub: 'මෙය මිනිත්තු 1ක් ගත වේ',
scan_place_leaf: 'රෝගී කොළය රාමුව ඇතුළට ගන්න',
scan_good_light: 'හොඳ ආලෝකය තිබෙන විට ගන්න',
scan_try_again: 'නැවත් උත්සාහ කරන්න',
scan_only_scan: 'කොළයක් විතරක් scan කරන්න',
// Results
results_title: 'Analysis Results',
results_sub: 'විශ්ලේෂණ ප්‍රතිඵල',
results_detected: 'හඳුනාගත් රෝගය',
results_captured: 'ග්‍රහණය කළ රූපය',
results_confidence: 'විශ්වාසය',
results_symptoms: 'රෝග ලක්ෂණ',
results_symptoms_sub: 'Symptoms',
results_treatment_steps: 'ප්‍රතිකාර පියවර',
results_treatment_sub: 'Treatment Steps',
results_chemical: 'රසායනික ප්‍රතිකාර',
results_organic: 'කාබනික ප්‍රතිකාර',
results_prevention: 'වැළැක්වීම',
results_view_details: 'View Full Details',
results_view_details_sub: 'සම්පූර්ණ තොරතුරු බලන්න',
results_heatmap: 'Check Outbreak Map',
results_heatmap_sub: 'ව්‍යාප්ති සිතියම බලන්න',
results_scan_again: 'නැවත ස්කෑන් කරන්න',
results_unknown: 'හඳුනාගත නොහැකි රෝගයක්',
results_unknown_symptoms: 'පැහැදිලි රෝග ලක්ෂණ නොමැත',
results_unknown_consult: 'කෘෂිකර්ම නිලධාරියකු හමුවන්න',
results_unknown_tip: 'හොඳ ආලෝකයකදී කොළයක් scan කරන්න',
// Detail page
detail_symptoms: 'රෝග ලක්ෂණ / Symptoms',
detail_env: 'වාතාවරණ සාධක / Environmental Factors',
detail_warning: 'අනතුරු ලකුණු',
detail_prevention: 'වැළැක්වීමේ ඉඟි / Prevention Tips',
detail_treatment: 'ප්‍රතිකාර පියවර / Treatment Steps',
detail_back: '← ආපසු',
detail_favorable: 'අනුකූල',
detail_high_risk: 'ඉහළ අවදානම',
detail_moderate: 'මධ්‍යම',
detail_normal: 'සාමාන්‍ය',
detail_season: 'කාලය',
detail_warning1: 'කොළ කහ හෝ දුඹුරු වීම',
detail_warning2: 'කොළ මත කළු ලප හෝ තුවාල',
detail_warning3: 'වර්ධනය මන්දගාමී හෝ මැලවීම',
detail_warning4: 'ධාන්‍ය හෝ පළතුරු වර්ණ වෙනස් වීම',
detail_prev1: 'රෝගී ශාක කොටස් නිතිපතා ඉවත් කරන්න',
detail_prev2: 'අවදානම් කාලවලදී fungicide ඉසින්න',
detail_prev3: 'ප්‍රතිරෝධී ප්‍රභේද භාවිතා කරන්න',
detail_step1: 'රෝගී කොළ සහ ශාක කොටස් ඉවත් කරලා දහනය කරන්න',
detail_step4: 'සතිය ගණනකට පසු නැවත ශාක නිරීක්ෂණය කරන්න',
  },
  en: {
    app_name: 'Govi Nena',
    tagline: 'Smart Farming Assistant',
    subtitle: 'Your Crop Health Assistant',
    subtitle2: 'Powered by AI',
    sign_in: 'Sign In',
    sign_in_sub: 'Access your account',
    phone: 'Phone Number',
    password: 'Password',
    forgot: 'Forgot Password?',
    login_btn: 'Sign In',
    no_account: "Don't have an account?",
    register_link: 'Register',
    footer: '🌾 Empowering Sri Lankan Farmers',
    register_title: 'Register',
    register_sub: 'Create your account',
    full_name: 'Full Name',
    district: 'District',
    district_placeholder: 'Select your district',
    register_btn: 'Create Account',
    has_account: 'Already have an account?',
    login_link: 'Sign In',
    districts: [
      'Colombo', 'Gampaha', 'Kalutara', 'Kandy', 'Matale', 'Nuwara Eliya',
      'Galle', 'Matara', 'Hambantota', 'Jaffna', 'Mannar', 'Vavuniya',
      'Anuradhapura', 'Polonnaruwa', 'Kurunegala', 'Puttalam', 'Badulla',
      'Monaragala', 'Ratnapura', 'Kegalle', 'Trincomalee', 'Batticaloa', 'Ampara'
    ],
    // Scan page
scan_select_crop: 'Select Crop',
scan_select_sub: 'For disease detection',
scan_upload_img: 'Upload a photo',
scan_diseases: 'diseases',
scan_loading: 'Loading model...',
scan_loading_sub: 'This may take a minute',
scan_place_leaf: 'Place diseased leaf inside frame',
scan_good_light: 'Take in good lighting',
scan_try_again: 'Try Again',
scan_only_scan: 'Only scan leaves',
// Results
results_title: 'Analysis Results',
results_sub: 'විශ්ලේෂණ ප්‍රතිඵල',
results_detected: 'Detected Disease',
results_captured: 'Captured Image',
results_confidence: 'Confidence',
results_symptoms: 'Symptoms',
results_symptoms_sub: 'රෝග ලක්ෂණ',
results_treatment_steps: 'Treatment Steps',
results_treatment_sub: 'ප්‍රතිකාර පියවර',
results_chemical: 'Chemical Treatment',
results_organic: 'Organic Treatment',
results_prevention: 'Prevention',
results_view_details: 'View Full Details',
results_view_details_sub: 'සම්පූර්ණ තොරතුරු බලන්න',
results_heatmap: 'Check Outbreak Map',
results_heatmap_sub: 'ව්‍යාප්ති සිතියම බලන්න',
results_scan_again: 'Scan Again',
results_unknown: 'Disease Not Identified',
results_unknown_symptoms: 'No clear symptoms detected',
results_unknown_consult: 'Consult an agriculture officer',
results_unknown_tip: 'Try scanning a leaf in good lighting',
// Detail page
detail_symptoms: 'Symptoms / රෝග ලක්ෂණ',
detail_env: 'Environmental Factors / වාතාවරණ සාධක',
detail_warning: 'Warning Signs',
detail_prevention: 'Prevention Tips / වැළැක්වීමේ ඉඟි',
detail_treatment: 'Treatment Steps / ප්‍රතිකාර පියවර',
detail_back: '← Go Back',
detail_favorable: 'Favorable',
detail_high_risk: 'High Risk',
detail_moderate: 'Moderate',
detail_normal: 'Normal',
detail_season: 'Season',
detail_warning1: 'Yellowing or browning of leaves',
detail_warning2: 'Dark spots or lesions on foliage',
detail_warning3: 'Stunted growth or wilting',
detail_warning4: 'Fruit or grain discoloration',
detail_prev1: 'Remove infected plant debris regularly',
detail_prev2: 'Apply preventive fungicide during high-risk periods',
detail_prev3: 'Use disease-resistant crop varieties when available',
detail_step1: 'Remove and burn infected leaves and plant parts immediately',
detail_step4: 'Re-inspect plants after one week for improvement',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('si');
  const toggleLang = () => setLang(prev => prev === 'si' ? 'en' : 'si');

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}